
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SPACE = 46;
  public static final int REL_OP = 19;
  public static final int INCREMENT = 44;
  public static final int CONST = 10;
  public static final int SLASH = 39;
  public static final int CDOTS = 34;
  public static final int CASE = 5;
  public static final int CLOSE_SQUARE = 27;
  public static final int DECREMENT = 45;
  public static final int FOR = 13;
  public static final int MINUS = 21;
  public static final int BAR = 38;
  public static final int TYPE = 12;
  public static final int ASTRISK = 35;
  public static final int OPEN_PARAN = 22;
  public static final int LESS_DASH = 41;
  public static final int COMMA = 29;
  public static final int OPEN_SQUARE = 26;
  public static final int OR_OP = 17;
  public static final int OPEN_CURLY = 24;
  public static final int PLUS = 20;
  public static final int AMBERSAND = 42;
  public static final int EXCLAMATION = 40;
  public static final int IF = 11;
  public static final int DOT = 30;
  public static final int AND_OP = 18;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int EQUAL = 33;
  public static final int error = 1;
  public static final int PERCENT = 43;
  public static final int NEWLINE = 47;
  public static final int SEMI_COLON = 28;
  public static final int BREAK = 2;
  public static final int ERROR = 48;
  public static final int SHIFT_LEFT = 36;
  public static final int SWITCH = 9;
  public static final int CLOSE_PARAN = 23;
  public static final int IMPORT = 14;
  public static final int COLON = 31;
  public static final int CLOSE_CURLY = 25;
  public static final int ELSE = 7;
  public static final int FUNC = 4;
  public static final int PACKAGE = 8;
  public static final int DEFAULT = 3;
  public static final int STRUCT = 6;
  public static final int STRING_LIT = 50;
  public static final int INT_LIT = 51;
  public static final int SHIFT_RIGHT = 37;
  public static final int VAR = 16;
  public static final int COLON_EQUAL = 32;
  public static final int IDENTIFIER = 49;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BREAK",
  "DEFAULT",
  "FUNC",
  "CASE",
  "STRUCT",
  "ELSE",
  "PACKAGE",
  "SWITCH",
  "CONST",
  "IF",
  "TYPE",
  "FOR",
  "IMPORT",
  "RETURN",
  "VAR",
  "OR_OP",
  "AND_OP",
  "REL_OP",
  "PLUS",
  "MINUS",
  "OPEN_PARAN",
  "CLOSE_PARAN",
  "OPEN_CURLY",
  "CLOSE_CURLY",
  "OPEN_SQUARE",
  "CLOSE_SQUARE",
  "SEMI_COLON",
  "COMMA",
  "DOT",
  "COLON",
  "COLON_EQUAL",
  "EQUAL",
  "CDOTS",
  "ASTRISK",
  "SHIFT_LEFT",
  "SHIFT_RIGHT",
  "BAR",
  "SLASH",
  "EXCLAMATION",
  "LESS_DASH",
  "AMBERSAND",
  "PERCENT",
  "INCREMENT",
  "DECREMENT",
  "SPACE",
  "NEWLINE",
  "ERROR",
  "IDENTIFIER",
  "STRING_LIT",
  "INT_LIT"
  };
}

